// Generated by scripts/build_airports.py -- do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::airports {

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
};

struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
};

namespace large {
constexpr size_t kAirportCount = 1160;
constexpr size_t kRunwayCount = 1705;
extern const Airport kAirports[];
extern const Runway kRunways[];
}  // namespace large

namespace medium {
constexpr size_t kAirportCount = 3801;
constexpr size_t kRunwayCount = 4638;
extern const Airport kAirports[];
extern const Runway kRunways[];
}  // namespace medium

}  // namespace data::airports
